<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('products')->insert([
            [
                'id' => 1,
                'name' => 'Wuling Air Ev',
                'slug' => 'wuling-air-ev',
                'category_id' => 1,
                'thumbnail' => 'products/product-wuling.png',
                'description' => 'Wuling Air EV 2025 adalah 4 Seater Hatchback yang tersedia dalam daftar harga Rp 214 - 307,5 Juta di Indonesia. Dimensi Air EV adalah 2974 mm L x 1505 mm W x 1631 mm H. Lebih dari 1 pengguna telah memberikan penilaian untuk Air EV berdasarkan fitur, jarak tempuh, kenyamanan tempat duduk dan kinerja mesin. Pesaing terdekat Wuling Air EV adalah Agya, Brio, Sirion dan S-Presso.',
                'battery_capacity' => 27,
                'power' => 40,
                'price' => 245000,
                'status' => 'ready',
                'deleted_at' => null,
                'created_at' => '2025-06-05 21:25:49',
                'updated_at' => '2025-06-05 21:25:49',
            ],
            [
                'id' => 2,
                'name' => 'Polytron Fox-R',
                'slug' => 'polytron-fox-r',
                'category_id' => 2,
                'thumbnail' => 'products/product-polytron-fox-r-slant-rear-view-full-image-444870.jpg',
                'description' => 'Harga Polytron Fox-R 2025 di Indonesia dimulai dari Rp 20,5 Juta. Tersedia dalam 4 pilihan warna dan 1 varian di Indonesia. Rem depan menggunakan Disc , sedangkan di belakang Disc . Lebih dari 1 pengguna telah memberikan penilaian untuk Fox-R berdasarkan fitur, jarak tempuh, kenyamanan tempat duduk dan kinerja mesin. Pesaing terdekat Polytron Fox-R adalah Scoopy, Vario 125, Dazz dan Neo XR.',
                'battery_capacity' => 4,
                'power' => 30,
                'price' => 135000,
                'status' => 'ready',
                'deleted_at' => null,
                'created_at' => '2025-06-05 21:27:55',
                'updated_at' => '2025-06-05 21:27:55',
            ],
            [
                'id' => 3,
                'name' => 'BYD M6',
                'slug' => 'byd-m6',
                'category_id' => 1,
                'thumbnail' => 'products/product-byd-m6-front-angle-low-view-779791.jpg',
                'description' => 'BYD M6 2025 adalah 7 dan 6 Seater MPV yang tersedia dalam daftar harga Rp 383 - 433 Juta di Indonesia. Dimensi M6 adalah 4710 mm L x 1810 mm W x 1690 mm H. Pesaing terdekat BYD M6 adalah Kijang Innova, Livina , Xpander dan Veloz.',
                'battery_capacity' => 10,
                'power' => 60,
                'price' => 383000,
                'status' => 'ready',
                'deleted_at' => null,
                'created_at' => '2025-06-05 21:30:10',
                'updated_at' => '2025-06-05 21:30:10',
            ],
            [
                'id' => 4,
                'name' => 'Wuling Binguo EV',
                'slug' => 'wuling-binguo-ev',
                'category_id' => 1,
                'thumbnail' => 'products/product-wuling-binguo-ev-color-920074.jpg',
                'description' => 'Wuling Binguo EV 2025 adalah 5 Seater Hatchback yang tersedia dalam daftar harga Rp 310 - 413 Juta di Indonesia. Dimensi Binguo EV adalah 3950 mm L x 1708 mm W x 1580 mm H. Lebih dari 3 pengguna telah memberikan penilaian untuk Binguo EV berdasarkan fitur, jarak tempuh, kenyamanan tempat duduk dan kinerja mesin. Pesaing terdekat Wuling Binguo EV adalah Agya, Yaris, Brio dan City Hatchbook.',
                'battery_capacity' => 38,
                'power' => 67,
                'price' => 235000,
                'status' => 'ready',
                'deleted_at' => null,
                'created_at' => '2025-06-05 21:31:36',
                'updated_at' => '2025-06-05 21:31:36',
            ],
            [
                'id' => 5,
                'name' => 'Tesla X Model',
                'slug' => 'tesla-x-model',
                'category_id' => 1,
                'thumbnail' => 'products/product-tesla-model-x-color-996384.jpg',
                'description' => 'Tesla Model X 2025 adalah 5 seater SUV. Pesaing terdekat Tesla Model X adalah Q5, GLB-Class, Palisade dan bZ4X.',
                'battery_capacity' => 100,
                'power' => 1020,
                'price' => 360000,
                'status' => 'ready',
                'deleted_at' => null,
                'created_at' => '2025-06-05 21:42:14',
                'updated_at' => '2025-06-05 21:42:14',
            ],
            [
                'id' => 6,
                'name' => 'Gesits Electric',
                'slug' => 'gesits-electric',
                'category_id' => 2,
                'thumbnail' => 'products/product-gesits-electric-slant-rear-view-full-image-100724.jpg',
                'description' => 'Harga Gesits Electric 2025 di Indonesia dimulai dari Rp 28,7 Juta. Terdapat dalam 1 varian di Indonesia. Rem depan menggunakan Disc , sedangkan di belakang Disc . Lebih dari 3 pengguna telah memberikan penilaian untuk Electric berdasarkan fitur, jarak tempuh, kenyamanan tempat duduk dan kinerja mesin. Pesaing terdekat Gesits Electric adalah Scoopy, Vario 125, Neo XR dan Rockz.',
                'battery_capacity' => 35,
                'power' => 7,
                'price' => 145000,
                'status' => 'ready',
                'deleted_at' => null,
                'created_at' => '2025-06-05 21:43:49',
                'updated_at' => '2025-06-05 21:43:49',
            ],
            [
                'id' => 7,
                'name' => 'Alva CERVO',
                'slug' => 'alva-cervo',
                'category_id' => 2,
                'thumbnail' => 'products/product-alva-cervo-slant-front-view-full-image-983260.jpg',
                'description' => 'Alva CERVO 2025 tersedia dalam rentang harga Rp 37,75 Juta di Indonesia. Terdapat dalam 4 varian di Indonesia. Rem depan menggunakan Disc , sedangkan di belakang Disc . Lebih dari 6 pengguna telah memberikan penilaian untuk CERVO berdasarkan fitur, jarak tempuh, kenyamanan tempat duduk dan kinerja mesin. Pesaing terdekat Alva CERVO adalah Zafferano 250, Medley, Django 150 dan LX',
                'battery_capacity' => 24,
                'power' => 13,
                'price' => 170000,
                'status' => 'ready',
                'deleted_at' => null,
                'created_at' => '2025-06-05 21:45:28',
                'updated_at' => '2025-06-05 21:45:28',
            ],
            [
                'id' => 8,
                'name' => 'Alva One',
                'slug' => 'alva-one',
                'category_id' => 2,
                'thumbnail' => 'products/product-alva-one-slant-front-view-full-image-372680.jpg',
                'description' => 'Harga Alva One 2025 di Indonesia dimulai dari Rp 34,99 Juta. Terdapat dalam 1 varian di Indonesia. Rem depan menggunakan Disc , sedangkan di belakang Disc . Pesaing terdekat Alva One adalah Vario 125, Satria F150, Racing King 150i dan PCX160.',
                'battery_capacity' => 45,
                'power' => 5,
                'price' => 165000,
                'status' => 'ready',
                'deleted_at' => null,
                'created_at' => '2025-06-05 21:47:42',
                'updated_at' => '2025-06-05 21:47:42',
            ],
            [
                'id' => 9,
                'name' => 'Wuling Cloud EV',
                'slug' => 'wuling-cloud-ev',
                'category_id' => 1,
                'thumbnail' => 'products/product-wuling-cloud-front-angle-low-view-568299.jpg',
                'description' => 'Wuling Cloud EV 2025 adalah 5 Seater Crossover yang tersedia dalam daftar harga Rp 415 - 443 Juta di Indonesia. Dimensi Cloud EV adalah 4295 mm L x 1850 mm W x 1652 mm H. Pesaing terdekat Wuling Cloud EV adalah 2, Yaris, City Hatchback dan Binguo EV.',
                'battery_capacity' => 51,
                'power' => 134,
                'price' => 245000,
                'status' => 'ready',
                'deleted_at' => null,
                'created_at' => '2025-06-05 21:49:10',
                'updated_at' => '2025-06-05 21:49:10',
            ],
            [
                'id' => 10,
                'name' => 'BYD Seal',
                'slug' => 'byd-seal',
                'category_id' => 1,
                'thumbnail' => 'products/product-byd-seal-front-angle-low-view-332440.jpg',
                'description' => 'BYD Seal 2025 adalah 5 Seater Sedan yang tersedia dalam daftar harga Rp 639 - 750 Juta di Indonesia. Dimensi Seal adalah 4800 mm L x 1875 mm W x 1460 mm H. Lebih dari 2 pengguna telah memberikan penilaian untuk Seal berdasarkan fitur, jarak tempuh, kenyamanan tempat duduk dan kinerja mesin. Pesaing terdekat BYD Seal adalah 6 Sedan, 3 Sedan, Corolla Altis dan Civic RS.',
                'battery_capacity' => 83,
                'power' => 530,
                'price' => 430000,
                'status' => 'ready',
                'deleted_at' => null,
                'created_at' => '2025-06-05 21:50:39',
                'updated_at' => '2025-06-05 21:50:39',
            ],
            [
                'id' => 11,
                'name' => 'MG 4 EV',
                'slug' => 'mg-4-ev',
                'category_id' => 1,
                'thumbnail' => 'products/product-mg-4-ev-front-angle-low-view-153361.jpg',
                'description' => 'MG 4 EV 2025 adalah 5 Seater SUV yang tersedia dalam daftar harga Rp 299 - 405 Juta di Indonesia. Mobil ini memiliki ground clearance 117 mm dengan dimensi sebagai berikut: 4287 mm L x 1836 mm W x 1516 mm H. Pesaing terdekat MG 4 EV adalah BRV, Jimny, Glory i-Auto dan ZS.',
                'battery_capacity' => 51,
                'power' => 168,
                'price' => 335000,
                'status' => 'ready',
                'deleted_at' => null,
                'created_at' => '2025-06-05 21:52:25',
                'updated_at' => '2025-06-05 21:52:25',
            ],            
        ]);
    }
}

